'use client';

import React, { useState, useRef, useEffect } from 'react';
import { Copy, Download, Check, Sparkles, Share2, AlertCircle, Quote, Cpu, Newspaper, Loader2, Film, Layers, MessageSquare, LayoutGrid, Image as ImageIcon, RefreshCw, Zap } from 'lucide-react';
import { OmniNewsItem } from '@/services/newsFetcher';
import { INSTAGRAM_HANDLE, WEBSITE_DOMAIN } from '@/data/instagram';
import { toPng } from 'html-to-image';
import { ReelsVideoStudio } from './ReelsVideoStudio';
import { CarouselStudio } from './CarouselStudio';
import { TwitterThreadStudio } from './TwitterThreadStudio';
import { generateInStudioAiVisual } from '@/utils/aiImageGenerator';

import { PostContent } from '@/types/postContent';

interface Props {
  newsItem?: OmniNewsItem;
  postContent?: PostContent;
}

export const TEMPLATES = [
  { id: 't1', name: '01. HEADLINE DOMINANT', icon: Sparkles, color: '#CCFF00' },
  { id: 't2', name: '02. EDITORIAL ESSAY', icon: Newspaper, color: '#FFFFFF' },
  { id: 't3', name: '03. QUOTE SPOTLIGHT', icon: Quote, color: '#FFB800' },
  { id: 't4', name: '04. TECH DATA GRID', icon: Cpu, color: '#00F0FF' },
  { id: 't5', name: '05. LIST BREAKDOWN', icon: LayoutGrid, color: '#FF00AA' },
];

export const InstagramPostStudio: React.FC<Props> = ({ newsItem, postContent }) => {
  // Normalize item parameters
  const itemTitle = postContent?.headline || newsItem?.title || 'UNTITLED POST';
  const itemCategory = postContent?.category || newsItem?.category || 'TECH';
  const itemSummary = postContent?.body || newsItem?.summary || '';
  const itemTakeaway = postContent?.rayuTakeaway || newsItem?.rayuTakeaway || itemSummary;
  const itemType = postContent?.contentType || 'TAKE';

  const safeNewsItem = newsItem || {
    id: 'default',
    title: itemTitle,
    summary: itemSummary,
    fullArticleContent: itemSummary,
    keyFacts: [],
    rayuTakeaway: itemTakeaway,
    url: 'https://rayu-360.vercel.app',
    source: 'RAYU V2 STUDIO',
    category: itemCategory as any,
    region: 'GLOBAL',
    dateGroup: 'TODAY',
    publishedAt: 'JUST NOW',
    readTime: '2 MIN',
    imageUrl: '',
    badgeColor: '#CCFF00',
  };

  const [studioFormat, setStudioFormat] = useState<'single' | 'reels' | 'carousel' | 'twitter'>('single');
  const [selectedTemplate, setSelectedTemplate] = useState('t1');
  const [copied, setCopied] = useState(false);
  const [published, setPublished] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [aspectRatio, setAspectRatio] = useState<'1:1' | '4:5'>(postContent?.aspectRatio || '1:1');

  // Hybrid AI Generator Controls
  const [aiProvider, setAiProvider] = useState<'OPENAI' | 'GEMINI' | 'AUTO'>('AUTO');
  const [negativeZone, setNegativeZone] = useState<'bottom' | 'left'>('bottom');
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [generationStage, setGenerationStage] = useState<'idle' | 'analyzing' | 'rendering'>('idle');
  const [elapsedTimer, setElapsedTimer] = useState(0);
  const [generationTimeMs, setGenerationTimeMs] = useState<number | null>(null);
  const [apiNotice, setApiNotice] = useState<string | null>(null);
  const [activePrompt, setActivePrompt] = useState<string | null>(null);
  const [activeProvider, setActiveProvider] = useState<string | null>(null);
  const cardRef = useRef<HTMLDivElement | null>(null);
  const uploadInputRef = useRef<HTMLInputElement | null>(null);

  // Live Editable Text Overlay Controls
  const [editableTitle, setEditableTitle] = useState<string>(itemTitle);
  const [editableSummary, setEditableSummary] = useState<string>(itemSummary);
  const [editableTakeaway, setEditableTakeaway] = useState<string>(itemTakeaway);

  // Reset editable text whenever item parameters change
  useEffect(() => {
    setEditableTitle(itemTitle);
    setEditableSummary(itemSummary);
    setEditableTakeaway(itemTakeaway);
  }, [itemTitle, itemSummary, itemTakeaway]);

  // Custom image upload state
  const initialImage = postContent?.sourceImage || newsItem?.imageUrl || null;
  const isUploadedImage = initialImage ? initialImage.startsWith('data:') : false;

  const [uploadedImageUrl, setUploadedImageUrl] = useState<string | null>(isUploadedImage ? initialImage : null);
  const [customImageUrl, setCustomImageUrl] = useState<string | null>(initialImage);
  const [isDragOver, setIsDragOver] = useState(false);
  const [imageSource, setImageSource] = useState<'ai' | 'upload'>(isUploadedImage ? 'upload' : 'ai');

  // Preserve uploaded image on item change
  useEffect(() => {
    const srcImg = postContent?.sourceImage || newsItem?.imageUrl;
    if (srcImg && srcImg.startsWith('data:')) {
      setUploadedImageUrl(srcImg);
      setCustomImageUrl(srcImg);
      setImageSource('upload');
      setImageLoaded(true);
    }
  }, [postContent?.sourceImage, newsItem?.imageUrl]);

  // One-shot auto-generation on first mount in V2 mode (postContent provided, no pre-existing image)
  const hasAutoGeneratedOnMount = React.useRef(false);
  useEffect(() => {
    if (
      !hasAutoGeneratedOnMount.current &&
      postContent &&
      !postContent.sourceImage &&
      imageSource === 'ai'
    ) {
      hasAutoGeneratedOnMount.current = true;
      handleGenerateServerAiBackground();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Re-generate if user changes AI provider or negative zone (only if already in AI mode with no image)
  const prevAiProvider = React.useRef(aiProvider);
  const prevNegativeZone = React.useRef(negativeZone);
  useEffect(() => {
    const providerChanged = prevAiProvider.current !== aiProvider;
    const zoneChanged = prevNegativeZone.current !== negativeZone;
    prevAiProvider.current = aiProvider;
    prevNegativeZone.current = negativeZone;
    if ((providerChanged || zoneChanged) && imageSource === 'ai' && customImageUrl && !isGeneratingAI) {
      handleGenerateServerAiBackground();
    }
  }, [aiProvider, negativeZone]);

  // Elapsed timer tracking
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isGeneratingAI) {
      setElapsedTimer(0);
      interval = setInterval(() => {
        setElapsedTimer((prev) => +(prev + 0.1).toFixed(1));
      }, 100);
    }
    return () => clearInterval(interval);
  }, [isGeneratingAI]);

  const [generationError, setGenerationError] = useState<string | null>(null);

  // Two-Stage AI Content Analysis + Image Generation Pipeline
  const handleGenerateServerAiBackground = async () => {
    setIsGeneratingAI(true);
    setGenerationStage('analyzing');
    setApiNotice(null);
    setActivePrompt(null);
    setGenerationError(null);
    const startTime = performance.now();

    try {
      setGenerationStage('analyzing');
      const res = await fetch('/api/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: itemTitle,
          category: itemCategory,
          summary: itemSummary,
          storyUrl: postContent?.sourceUrl || newsItem?.url,
          storyImageUrl: postContent?.sourceImage || newsItem?.imageUrl,
          fullArticleContent: postContent?.body || newsItem?.fullArticleContent,
          provider: aiProvider,
          layout: negativeZone,
        }),
      });

      setGenerationStage('rendering');
      const data = await res.json();

      if (res.ok && data.success && data.imageUrl) {
        setCustomImageUrl(data.imageUrl);
        setActiveProvider(data.provider || null);
        if (data.promptUsed) setActivePrompt(data.promptUsed);
        if (data.notice) setApiNotice(data.notice);
      } else {
        const errorMsg = data.error || `Server HTTP ${res.status}: ${res.statusText}`;
        console.error('[RAYU Studio] Image generation failed:', errorMsg, data.providerErrors);
        setGenerationError(errorMsg);
        setCustomImageUrl(null); // Do not use fake/canvas fallback
      }
    } catch (err: any) {
      console.error('[RAYU Studio] Network or fatal error during generation:', err);
      setGenerationError(`Network Error: ${err.message || String(err)}`);
      setCustomImageUrl(null); // Do not use fake/canvas fallback
    } finally {
      const endTime = performance.now();
      const duration = +((endTime - startTime) / 1000).toFixed(2);
      setGenerationTimeMs(duration > 0 ? duration : 1.2);
      setIsGeneratingAI(false);
      setGenerationStage('idle');
    }
  };

  // Handle custom image upload
  const handleImageUpload = (file: File) => {
    if (!file.type.startsWith('image/')) return;
    const reader = new FileReader();
    reader.onload = async (e) => {
      const dataUrl = e.target?.result as string;
      setUploadedImageUrl(dataUrl);
      setCustomImageUrl(dataUrl);
      setImageSource('upload');
      setImageLoaded(true); // Mark loaded immediately for uploaded data URLs
      setImageLoadError(null);

      // Trigger OCR & AI visual analysis on the uploaded image
      try {
        setApiNotice('⚡ AI ANALYZING UPLOADED IMAGE CONTENT & TEXT...');
        const res = await fetch('/api/analyze-image', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ imageBase64: dataUrl }),
        });
        if (res.ok) {
          const data = await res.json();
          if (data.success && data.title) {
            setEditableTitle(data.title);
            if (data.summary) setEditableSummary(data.summary);
            if (data.rayuTakeaway) setEditableTakeaway(data.rayuTakeaway);
            setApiNotice(`✅ AI EXTRACTED HEADLINE: "${data.title}"`);
          }
        }
      } catch (err) {
        console.warn('OCR error during upload:', err);
      }
    };
    reader.readAsDataURL(file);
  };

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) handleImageUpload(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) handleImageUpload(file);
  };

  const handleClearUpload = () => {
    setUploadedImageUrl(null);
    setImageSource('ai');
    if (uploadInputRef.current) uploadInputRef.current.value = '';
    handleGenerateServerAiBackground();
  };

  // Treat local/static paths and base64 data URLs as already loaded — no need to wait for onLoad
  const isInstantImage = (url: string | null) =>
    !url ? false : url.startsWith('data:') || url.startsWith('/') || url.startsWith('blob:');

  const [imageLoaded, setImageLoaded] = useState(() => isInstantImage(initialImage));
  const [imageLoadError, setImageLoadError] = useState<string | null>(null);

  // Reset image loaded state when URL changes — skip waiting for local/base64 images
  useEffect(() => {
    if (isInstantImage(customImageUrl)) {
      setImageLoaded(true);
    } else {
      setImageLoaded(false);
    }
    setImageLoadError(null);
  }, [customImageUrl]);

  // Image load error handler — NO silent canvas fallback!
  const handleImageError = () => {
    console.error('[RAYU Studio] Failed to load image from URL:', customImageUrl);
    setImageLoadError('Failed to load background image from target URL.');
  };

  const activeDisplayImage = customImageUrl || safeNewsItem.imageUrl || '';

  // Generate Instagram Caption
  const instagramCaption = `⚡ RAYU SOCIAL STREAM: [${safeNewsItem.category}]

${safeNewsItem.title.toUpperCase()}

📍 Region: ${safeNewsItem.region}
⏱️ Published: ${safeNewsItem.publishedAt}

Summary:
${safeNewsItem.summary}

💡 RAYU'S UNFILTERED TAKEAWAY:
"${safeNewsItem.rayuTakeaway || safeNewsItem.summary}"

🔗 Full analysis & primary sources live at ${WEBSITE_DOMAIN}
Link in bio 👉 @${INSTAGRAM_HANDLE}

#RAYU #thisisrayu #IndiaTech #TechNews #GlobalShift #${safeNewsItem.category} #${safeNewsItem.region}`;

  const handleCopyCaption = () => {
    navigator.clipboard.writeText(instagramCaption);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePublishSimulated = () => {
    setPublished(true);
    setTimeout(() => setPublished(false), 3000);
  };

  const handleDownloadCard = async () => {
    if (!cardRef.current) return;
    setIsDownloading(true);

    try {
      // Step 1: If the background image is an external URL (Pollinations/etc),
      // fetch it and convert to base64 first to avoid canvas CORS taint
      let resolvedImageUrl = activeDisplayImage;

      if (
        activeDisplayImage &&
        !activeDisplayImage.startsWith('data:') &&
        !activeDisplayImage.startsWith('blob:')
      ) {
        try {
          const proxyRes = await fetch(
            `/api/proxy-image?url=${encodeURIComponent(activeDisplayImage)}`
          );
          if (proxyRes.ok) {
            const { dataUrl } = await proxyRes.json();
            if (dataUrl) resolvedImageUrl = dataUrl;
          }
        } catch {
          // If proxy fails, try direct fetch
          try {
            const imgRes = await fetch(activeDisplayImage);
            const blob = await imgRes.blob();
            resolvedImageUrl = await new Promise<string>((resolve) => {
              const reader = new FileReader();
              reader.onloadend = () => resolve(reader.result as string);
              reader.readAsDataURL(blob);
            });
          } catch {
            // Keep original URL and hope html-to-image handles it
          }
        }
      }

      // Step 2: Temporarily swap image src to resolved base64 for clean export
      const imgEl = cardRef.current.querySelector('img') as HTMLImageElement | null;
      const originalSrc = imgEl?.src;
      if (imgEl && resolvedImageUrl !== activeDisplayImage) {
        imgEl.src = resolvedImageUrl;
        // Give browser time to render the new src
        await new Promise((r) => setTimeout(r, 300));
      }

      // Step 3: Export card as PNG
      const pngDataUrl = await toPng(cardRef.current, {
        quality: 1.0,
        pixelRatio: 3,
        cacheBust: true,
        skipFonts: false,
      });

      // Step 4: Restore original src
      if (imgEl && originalSrc) imgEl.src = originalSrc;

      // Step 5: Trigger download
      const link = document.createElement('a');
      link.download = `rayu-post-${selectedTemplate}-${safeNewsItem.id}.png`;
      link.href = pngDataUrl;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

    } catch (err) {
      console.error('Download failed:', err);
      // Last resort: try downloading the background image directly
      if (activeDisplayImage) {
        try {
          const res = await fetch(activeDisplayImage);
          const blob = await res.blob();
          const blobUrl = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.download = `rayu-post-${safeNewsItem.id}.jpg`;
          link.href = blobUrl;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          URL.revokeObjectURL(blobUrl);
        } catch {
          alert('Download failed. Please try right-clicking the image and saving it manually.');
        }
      }
    } finally {
      setIsDownloading(false);
    }
  };

  // Clone normalized item with active AI background & live editable text
  const dynamicNewsItem: OmniNewsItem = {
    id: postContent?.id || newsItem?.id || `v2-${Date.now()}`,
    title: editableTitle.trim() || itemTitle,
    summary: editableSummary.trim() || itemSummary,
    fullArticleContent: editableSummary.trim() || itemSummary,
    keyFacts: ['V2 Studio Content'],
    rayuTakeaway: editableTakeaway.trim() || itemTakeaway,
    category: itemCategory as any,
    region: 'GLOBAL',
    publishedAt: 'JUST NOW',
    readTime: '2 MIN',
    url: postContent?.sourceUrl || newsItem?.url || WEBSITE_DOMAIN,
    source: 'RAYU V2 STUDIO',
    dateGroup: 'TODAY',
    imageUrl: activeDisplayImage,
    badgeColor: '#CCFF00',
  };

  return (
    <div className="bg-[#0B0B0B] border border-white/10 p-3 sm:p-6 md:p-8 rounded-sm text-white">
      {/* Hybrid AI Background Art Generator Control Bar */}
      <div className="mb-6 p-4 sm:p-5 bg-[#050505] border border-[#CCFF00]/40 rounded-sm space-y-4 shadow-[0_0_25px_rgba(204,255,0,0.1)]">
        <div className="flex flex-col gap-4">
          {/* Header row */}
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded bg-[#CCFF00]/10 border border-[#CCFF00]/40 flex items-center justify-center text-[#CCFF00] shrink-0">
              {isGeneratingAI ? <Loader2 size={18} className="animate-spin text-[#CCFF00]" /> : <Zap size={18} />}
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-1.5 text-[10px] sm:text-xs font-mono font-bold text-[#CCFF00] uppercase">
                <Sparkles size={12} />
                <span className="truncate">AI VISUAL ENGINE: ANALYZE → RENDER</span>
              </div>
              <span className="text-[10px] font-mono text-neutral-400 leading-snug">
                {isGeneratingAI
                  ? generationStage === 'analyzing'
                    ? `READING STORY... (${elapsedTimer}s)`
                    : `RENDERING IMAGE... (${elapsedTimer}s)`
                  : activeProvider
                  ? `${activeProvider} · ${generationTimeMs || 1.2}s`
                  : `READY IN ${generationTimeMs || 1.2}s`}
              </span>
            </div>
          </div>

          {/* Controls row — scrollable on mobile */}
          <div className="flex flex-wrap items-center gap-2 overflow-x-auto pb-1">
            {/* AI Provider Switcher */}
            <div className="flex items-center bg-[#090909] border border-white/15 rounded-sm p-0.5 text-[10px] sm:text-xs font-mono shrink-0">
              <button
                onClick={() => setAiProvider('OPENAI')}
                className={`px-2 sm:px-3 py-1.5 rounded-sm font-bold uppercase transition-all ${
                  aiProvider === 'OPENAI' ? 'bg-[#CCFF00] text-black' : 'text-neutral-400 hover:text-white'
                }`}
              >
                DALL·E
              </button>
              <button
                onClick={() => setAiProvider('GEMINI')}
                className={`px-2 sm:px-3 py-1.5 rounded-sm font-bold uppercase transition-all ${
                  aiProvider === 'GEMINI' ? 'bg-[#CCFF00] text-black' : 'text-neutral-400 hover:text-white'
                }`}
              >
                GEMINI
              </button>
            </div>

            {/* Negative Space Zone */}
            <div className="flex items-center bg-[#090909] border border-white/15 rounded-sm p-0.5 text-[10px] sm:text-xs font-mono shrink-0">
              <button
                onClick={() => setNegativeZone('bottom')}
                className={`px-2 sm:px-3 py-1.5 rounded-sm uppercase ${
                  negativeZone === 'bottom' ? 'bg-white/20 text-white font-bold' : 'text-neutral-500'
                }`}
              >
                BOTTOM
              </button>
              <button
                onClick={() => setNegativeZone('left')}
                className={`px-2 sm:px-3 py-1.5 rounded-sm uppercase ${
                  negativeZone === 'left' ? 'bg-white/20 text-white font-bold' : 'text-neutral-500'
                }`}
              >
                LEFT
              </button>
            </div>

            <button
              onClick={handleGenerateServerAiBackground}
              disabled={isGeneratingAI}
              className="inline-flex items-center gap-2 text-[10px] sm:text-xs font-mono font-bold bg-[#CCFF00] text-black hover:bg-[#b5e600] px-3 sm:px-4 py-2.5 rounded-sm transition-colors uppercase cursor-pointer disabled:opacity-50 shrink-0 w-full sm:w-auto justify-center"
            >
              <RefreshCw size={13} className={isGeneratingAI ? 'animate-spin' : ''} />
              <span>{isGeneratingAI ? `GENERATING (${elapsedTimer}s)...` : 'RE-ROLL AI ART 🎨'}</span>
            </button>
          </div>
        </div>

        {/* Explicit Generation Error Banner */}
        {generationError && !isGeneratingAI && (
          <div className="p-3.5 bg-red-950/60 border border-red-500/80 rounded-sm text-xs font-mono text-red-200 space-y-1">
            <div className="flex items-center gap-2 font-bold text-red-400 uppercase">
              <AlertCircle size={14} />
              <span>AI GENERATION FAILED (NO SILENT FALLBACK)</span>
            </div>
            <div className="text-red-300 break-words font-semibold">{generationError}</div>
            <div className="text-[10px] text-red-400/80 pt-1 border-t border-red-500/20">
              Check your API key scope in .env.local or select AUTO / Pollinations AI provider.
            </div>
          </div>
        )}

        {/* Explicit Image Load Error Banner */}
        {imageLoadError && (
          <div className="p-3 bg-red-950/40 border border-red-500/50 rounded-sm text-xs font-mono text-red-300 flex items-center gap-2">
            <AlertCircle size={14} className="text-red-400 shrink-0" />
            <span>{imageLoadError}</span>
          </div>
        )}

        {/* AI-Generated Scene Prompt Display */}
        {activePrompt && !isGeneratingAI && (
          <div className="p-3 bg-[#0a0a0a] border border-[#CCFF00]/20 rounded-sm">
            <div className="text-[10px] font-mono text-[#CCFF00] uppercase mb-1.5 flex items-center gap-1.5">
              <Sparkles size={10} />
              <span>AI CONTENT ANALYSIS → VISUAL SCENE DESCRIPTION:</span>
            </div>
            <p className="text-[11px] font-mono text-neutral-300 leading-relaxed italic">{activePrompt}</p>
          </div>
        )}
        {/* Custom Image Upload Zone */}
        <div className="border-t border-white/10 pt-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[10px] font-mono text-neutral-500 uppercase">OR UPLOAD YOUR OWN IMAGE:</span>
            {imageSource === 'upload' && uploadedImageUrl && (
              <button
                onClick={handleClearUpload}
                className="text-[10px] font-mono text-red-400 hover:text-red-300 uppercase flex items-center gap-1 transition-colors"
              >
                <span>✕</span>
                <span>CLEAR — USE AI IMAGE</span>
              </button>
            )}
          </div>

          {/* Hidden file input */}
          <input
            ref={uploadInputRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={handleFileInputChange}
          />

          {uploadedImageUrl && imageSource === 'upload' ? (
            /* Uploaded image preview */
            <div className="flex items-center gap-4 p-3 bg-[#0a0a0a] border border-white/20 rounded-sm">
              <img
                src={uploadedImageUrl}
                alt="Uploaded"
                className="w-16 h-16 object-cover rounded-sm border border-white/20"
              />
              <div className="flex-1">
                <div className="text-[10px] font-mono text-[#CCFF00] uppercase font-bold mb-1">✅ CUSTOM IMAGE ACTIVE</div>
                <div className="text-[10px] font-mono text-neutral-400">Your uploaded image is being used as the post background</div>
              </div>
              <button
                onClick={() => uploadInputRef.current?.click()}
                className="text-[10px] font-mono text-neutral-400 hover:text-white px-3 py-1.5 border border-white/15 rounded-sm hover:border-white/40 transition-all uppercase"
              >
                CHANGE
              </button>
            </div>
          ) : (
            /* Drag & drop upload zone */
            <div
              onClick={() => uploadInputRef.current?.click()}
              onDragOver={(e) => { e.preventDefault(); setIsDragOver(true); }}
              onDragLeave={() => setIsDragOver(false)}
              onDrop={handleDrop}
              className={`flex flex-col items-center justify-center gap-2 p-5 border-2 border-dashed rounded-sm cursor-pointer transition-all ${
                isDragOver
                  ? 'border-[#CCFF00] bg-[#CCFF00]/5 scale-[1.01]'
                  : 'border-white/15 hover:border-white/35 hover:bg-white/[0.02]'
              }`}
            >
              <ImageIcon size={22} className={isDragOver ? 'text-[#CCFF00]' : 'text-neutral-500'} />
              <div className="text-center">
                <div className={`text-xs font-mono font-bold uppercase ${isDragOver ? 'text-[#CCFF00]' : 'text-neutral-400'}`}>
                  {isDragOver ? 'DROP TO UPLOAD' : 'DRAG & DROP OR CLICK TO UPLOAD'}
                </div>
                <div className="text-[10px] font-mono text-neutral-600 mt-0.5">PNG, JPG, WEBP — replaces AI background</div>
              </div>
            </div>
          )}
        </div>

        {/* Live Editable Text Overlay Controller */}
        <div className="border-t border-white/10 pt-4 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-mono font-bold text-[#CCFF00] uppercase flex items-center gap-1.5">
              <Sparkles size={11} />
              <span>LIVE CARD TEXT CONTROLLER (EDIT HEADLINE & OVERLAY REAL-TIME):</span>
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-12 gap-3">
            <div className="sm:col-span-6">
              <label className="block text-[9px] font-mono text-neutral-400 uppercase mb-1">
                CARD HEADLINE / TITLE:
              </label>
              <input
                type="text"
                value={editableTitle}
                onChange={(e) => setEditableTitle(e.target.value)}
                placeholder="Enter headline..."
                className="w-full bg-[#050505] border border-white/20 focus:border-[#CCFF00] px-3 py-2 text-xs font-bold text-white rounded-sm outline-none font-mono uppercase"
              />
            </div>

            <div className="sm:col-span-6">
              <label className="block text-[9px] font-mono text-neutral-400 uppercase mb-1">
                CARD SUBTITLE / SUMMARY:
              </label>
              <input
                type="text"
                value={editableSummary}
                onChange={(e) => setEditableSummary(e.target.value)}
                placeholder="Enter summary..."
                className="w-full bg-[#050505] border border-white/20 focus:border-[#CCFF00] px-3 py-2 text-xs text-neutral-300 rounded-sm outline-none font-mono"
              />
            </div>
          </div>
        </div>

        {apiNotice && (
          <div className="p-2.5 bg-yellow-500/10 border border-yellow-500/30 rounded-sm text-[11px] font-mono text-yellow-300 flex items-center justify-between">
            <span>💡 {apiNotice}</span>
            <span className="text-neutral-400">Keys stored in .env.local</span>
          </div>
        )}
      </div>

      {/* Format Selection Bar */}
      <div className="mb-6 border-b border-white/10 pb-5">
        <span className="text-[10px] sm:text-xs font-mono font-bold text-[#CCFF00] uppercase block mb-3">
          OUTPUT FORMAT:
        </span>
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => setStudioFormat('single')}
            className={`p-2.5 sm:p-3.5 rounded-sm border text-left flex items-center gap-2 transition-all cursor-pointer ${
              studioFormat === 'single'
                ? 'bg-[#CCFF00] text-black font-bold border-[#CCFF00]'
                : 'bg-[#050505] border-white/10 text-neutral-300 hover:border-white/30'
            }`}
          >
            <LayoutGrid size={14} />
            <span className="text-[10px] sm:text-xs font-mono uppercase">📸 SINGLE POST</span>
          </button>

          <button
            onClick={() => setStudioFormat('reels')}
            className={`p-2.5 sm:p-3.5 rounded-sm border text-left flex items-center gap-2 transition-all cursor-pointer ${
              studioFormat === 'reels'
                ? 'bg-[#CCFF00] text-black font-bold border-[#CCFF00]'
                : 'bg-[#050505] border-white/10 text-neutral-300 hover:border-white/30'
            }`}
          >
            <Film size={14} />
            <span className="text-[10px] sm:text-xs font-mono uppercase">🎬 AI REELS</span>
          </button>

          <button
            onClick={() => setStudioFormat('carousel')}
            className={`p-2.5 sm:p-3.5 rounded-sm border text-left flex items-center gap-2 transition-all cursor-pointer ${
              studioFormat === 'carousel'
                ? 'bg-[#CCFF00] text-black font-bold border-[#CCFF00]'
                : 'bg-[#050505] border-white/10 text-neutral-300 hover:border-white/30'
            }`}
          >
            <Layers size={14} />
            <span className="text-[10px] sm:text-xs font-mono uppercase">🎡 CAROUSEL</span>
          </button>

          <button
            onClick={() => setStudioFormat('twitter')}
            className={`p-2.5 sm:p-3.5 rounded-sm border text-left flex items-center gap-2 transition-all cursor-pointer ${
              studioFormat === 'twitter'
                ? 'bg-[#CCFF00] text-black font-bold border-[#CCFF00]'
                : 'bg-[#050505] border-white/10 text-neutral-300 hover:border-white/30'
            }`}
          >
            <MessageSquare size={14} />
            <span className="text-[10px] sm:text-xs font-mono uppercase">🧵 THREAD</span>
          </button>
        </div>
      </div>

      {/* RENDER FORMAT COMPONENT WITH DYNAMIC ITEM */}
      {studioFormat === 'reels' && <ReelsVideoStudio newsItem={dynamicNewsItem} />}
      {studioFormat === 'carousel' && <CarouselStudio newsItem={dynamicNewsItem} />}
      {studioFormat === 'twitter' && <TwitterThreadStudio newsItem={dynamicNewsItem} />}

      {/* SINGLE POST CARD FORMAT (DEFAULT) */}
      {studioFormat === 'single' && (
        <>
          {/* Studio Action Header */}
          <div className="flex flex-col gap-3 pb-5 mb-5 border-b border-white/10">
            <div>
              <div className="flex items-center gap-2 text-[10px] sm:text-xs font-mono font-bold text-[#CCFF00] uppercase mb-1">
                <Sparkles size={12} />
                <span>1080x1080 POST GENERATOR</span>
              </div>
              <h3 className="text-lg sm:text-xl font-bold uppercase tracking-tight">
                POST DESIGNER FOR @{INSTAGRAM_HANDLE}
              </h3>
            </div>

            <div className="grid grid-cols-2 sm:flex sm:flex-wrap items-center gap-2">
              <button
                onClick={handleCopyCaption}
                className="inline-flex items-center justify-center gap-2 text-[10px] sm:text-xs font-mono font-bold bg-[#050505] border border-white/15 px-3 py-2.5 rounded-sm hover:border-[#CCFF00] text-white hover:text-[#CCFF00] transition-colors uppercase cursor-pointer"
              >
                {copied ? <Check size={13} className="text-[#CCFF00]" /> : <Copy size={13} />}
                <span>{copied ? 'COPIED!' : 'COPY CAPTION'}</span>
              </button>

              <button
                onClick={handleDownloadCard}
                disabled={isDownloading}
                className="inline-flex items-center justify-center gap-2 text-[10px] sm:text-xs font-mono font-bold bg-[#050505] border border-white/15 px-3 py-2.5 rounded-sm hover:border-[#CCFF00] text-white hover:text-[#CCFF00] transition-colors uppercase cursor-pointer disabled:opacity-50"
              >
                {isDownloading ? <Loader2 size={13} className="animate-spin text-[#CCFF00]" /> : <Download size={13} />}
                <span>{isDownloading ? 'EXPORTING...' : 'DOWNLOAD PNG'}</span>
              </button>

              <button
                onClick={handlePublishSimulated}
                className="col-span-2 sm:col-span-1 cta-element btn-sweep inline-flex items-center justify-center gap-2 bg-[#CCFF00] text-[#050505] text-[10px] sm:text-xs font-bold uppercase tracking-wider px-4 py-2.5 rounded-sm hover:bg-[#b5e600] transition-colors cursor-pointer"
              >
                {published ? <Check size={13} /> : <Share2 size={13} />}
                <span>{published ? 'POSTED!' : 'PUBLISH TO INSTAGRAM'}</span>
              </button>
            </div>
          </div>

          {/* 5 Social Media Templates Selector Bar */}
          <div className="mb-8">
            <span className="text-xs font-mono font-bold text-neutral-400 uppercase block mb-3">
              SELECT DESIGN TEMPLATE (5 STYLES AVAILABLE):
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {TEMPLATES.map((t) => {
                const Icon = t.icon;
                const isSelected = selectedTemplate === t.id;
                return (
                  <button
                    key={t.id}
                    onClick={() => setSelectedTemplate(t.id)}
                    className={`p-3 rounded-sm border text-left flex items-center gap-2 transition-all cursor-pointer ${
                      isSelected
                        ? 'bg-[#CCFF00]/10 border-[#CCFF00] text-[#CCFF00] shadow-[0_0_12px_rgba(204,255,0,0.2)] font-bold'
                        : 'bg-[#050505] border-white/10 text-neutral-400 hover:text-white'
                    }`}
                  >
                    <Icon size={14} style={{ color: t.color }} />
                    <span className="text-xs font-mono uppercase">{t.name}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Left 1080x1080 Square Post Card Preview Container */}
            <div className="lg:col-span-6">
              <span className="text-xs font-mono font-bold text-neutral-400 uppercase block mb-3 flex items-center justify-between">
                <span>📸 LIVE 1080x1080 SQUARE POST CARD PREVIEW ({selectedTemplate.toUpperCase()})</span>
                {isGeneratingAI && <span className="text-[#CCFF00] font-mono animate-pulse">COMPOSITING AI ART ({elapsedTimer}s)...</span>}
              </span>

              <div
                ref={cardRef}
                className="relative aspect-square w-full bg-[#050505] border border-white/20 rounded-sm p-6 flex flex-col justify-between overflow-hidden shadow-2xl"
              >
                {/* Background AI Artwork Layer — with loading skeleton for slow Pollinations URLs */}
                {activeDisplayImage && (
                  <>
                    {/* Loading skeleton shown until image loads (only for AI images, not uploaded images) */}
                    {!imageLoaded && imageSource !== 'upload' && (
                      <div className="absolute inset-0 bg-gradient-to-br from-[#0d0d0d] via-[#111] to-[#0a0a0a] animate-pulse flex flex-col items-center justify-center gap-3">
                        <div className="w-16 h-16 rounded-full border-2 border-[#CCFF00]/30 border-t-[#CCFF00] animate-spin" />
                        <span className="text-[10px] font-mono text-[#CCFF00]/60 uppercase tracking-widest">GENERATING AI VISUAL...</span>
                        <span className="text-[9px] font-mono text-neutral-600">FLUX MODEL RENDERING</span>
                      </div>
                    )}
                    <img
                      key={activeDisplayImage}
                      src={activeDisplayImage}
                      alt={safeNewsItem.title}
                      onLoad={() => setImageLoaded(true)}
                      onError={handleImageError}
                      className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-700 ${
                        imageLoaded || imageSource === 'upload'
                          ? (isGeneratingAI ? 'opacity-20 scale-105' : 'opacity-40 scale-100')
                          : 'opacity-0'
                      }`}
                    />
                  </>
                )}

                {/* TEMPLATE 1: KINETIC MINIMAL */}
                {selectedTemplate === 't1' && (
                  <>
                    <div className="relative z-10 flex items-center justify-between border-b border-white/15 pb-4">
                      <div className="text-2xl font-black text-white">RAY<span className="text-[#CCFF00]">U.</span></div>
                      <div className="text-[10px] font-mono font-bold px-2.5 py-1 bg-[#CCFF00] text-black rounded-sm uppercase">[{dynamicNewsItem.category}]</div>
                    </div>
                    <div className="relative z-10 my-auto py-4">
                      <span className="text-[10px] font-mono text-[#CCFF00] uppercase block mb-2">● LIVE AWARENESS • {dynamicNewsItem.region}</span>
                      <h4 className="text-xl sm:text-2xl font-black text-white leading-tight uppercase mb-3 drop-shadow-md">{dynamicNewsItem.title}</h4>
                      <p className="text-xs text-neutral-200 line-clamp-3 leading-relaxed">{dynamicNewsItem.summary}</p>
                    </div>
                    <div className="relative z-10 pt-4 border-t border-white/15 flex items-center justify-between text-[10px] font-mono text-neutral-300">
                      <span className="text-[#CCFF00] font-bold">@THISISRAYU</span>
                      <span>RAYU-360.VERCEL.APP</span>
                    </div>
                  </>
                )}

                {/* TEMPLATE 2: EDITORIAL ESSAY */}
                {selectedTemplate === 't2' && (
                  <>
                    <div className="relative z-10 flex items-center justify-between border-b border-white/20 pb-3">
                      <span className="text-xs font-mono font-bold tracking-widest text-neutral-400 uppercase">RAYU EDITORIAL</span>
                      <span className="text-[10px] font-mono text-neutral-500 uppercase">{dynamicNewsItem.publishedAt}</span>
                    </div>
                    <div className="relative z-10 my-auto p-4 bg-[#090909]/90 border border-white/10 rounded-sm backdrop-blur-md">
                      <div className="text-[10px] font-mono text-[#CCFF00] mb-2 uppercase font-bold">[{dynamicNewsItem.category} ESSAY]</div>
                      <h4 className="text-2xl font-serif text-white font-bold leading-tight mb-3">{dynamicNewsItem.title}</h4>
                      <p className="text-xs text-neutral-300 leading-relaxed italic">"{dynamicNewsItem.rayuTakeaway || dynamicNewsItem.summary}"</p>
                    </div>
                    <div className="relative z-10 pt-3 border-t border-white/20 flex items-center justify-between text-[10px] font-mono">
                      <span className="text-white font-bold">BY RAYU (@THISISRAYU)</span>
                      <span className="text-[#CCFF00]">READ AT RAYU-360.VERCEL.APP</span>
                    </div>
                  </>
                )}

                {/* TEMPLATE 3: BREAKING ALERT */}
                {selectedTemplate === 't3' && (
                  <>
                    <div className="relative z-10 bg-red-500 text-black px-4 py-2 font-mono font-black text-xs uppercase tracking-widest flex items-center justify-between">
                      <span>⚡ BREAKING AWARENESS ALERT</span>
                      <span>[{dynamicNewsItem.region}]</span>
                    </div>
                    <div className="relative z-10 my-auto py-4">
                      <h4 className="text-2xl font-black text-white leading-tight uppercase mb-4 text-red-400">{dynamicNewsItem.title}</h4>
                      <div className="p-4 bg-red-950/80 border border-red-500/40 rounded-sm text-xs text-neutral-200 leading-relaxed font-mono backdrop-blur-md">
                        {dynamicNewsItem.summary}
                      </div>
                    </div>
                    <div className="relative z-10 pt-3 border-t border-red-500/40 flex items-center justify-between text-[10px] font-mono text-neutral-400">
                      <span className="text-red-400 font-bold">URGENT REPORTING</span>
                      <span className="text-white">@THISISRAYU</span>
                    </div>
                  </>
                )}

                {/* TEMPLATE 4: TECH DATA GRID */}
                {selectedTemplate === 't4' && (
                  <>
                    <div className="relative z-10 flex items-center justify-between font-mono text-[10px] border-b border-[#00F0FF]/30 pb-3 text-[#00F0FF]">
                      <span>SYSTEM_ID: RAYU-{dynamicNewsItem.id.toUpperCase()}</span>
                      <span>DATA_STREAM</span>
                    </div>
                    <div className="relative z-10 my-auto py-2">
                      <h4 className="text-xl font-mono font-bold text-[#00F0FF] uppercase mb-4">{dynamicNewsItem.title}</h4>
                      {dynamicNewsItem.keyFacts && dynamicNewsItem.keyFacts.length > 0 ? (
                        <div className="space-y-2">
                          {dynamicNewsItem.keyFacts.slice(0, 3).map((f, i) => (
                            <div key={i} className="text-xs font-mono text-neutral-300 bg-neutral-900/90 p-2.5 border border-white/10 rounded-sm backdrop-blur-md">
                              <span className="text-[#00F0FF] font-bold">[{i + 1}]</span> {f}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <p className="text-xs font-mono text-neutral-300">{dynamicNewsItem.summary}</p>
                      )}
                    </div>
                    <div className="relative z-10 pt-3 border-t border-[#00F0FF]/30 flex items-center justify-between text-[10px] font-mono text-neutral-400">
                      <span className="text-[#00F0FF]">TERMINAL_ACTIVE</span>
                      <span>@THISISRAYU</span>
                    </div>
                  </>
                )}

                {/* TEMPLATE 5: QUOTE SPOTLIGHT */}
                {selectedTemplate === 't5' && (
                  <>
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_rgba(255,184,0,0.2)_0%,_rgba(5,5,5,0.9)_80%)] pointer-events-none" />
                    <div className="relative z-10 text-center pt-2">
                      <span className="text-xs font-mono font-bold text-[#FFB800] uppercase tracking-widest">SPOTLIGHT TAKEAWAY</span>
                    </div>
                    <div className="relative z-10 my-auto text-center px-4">
                      <Quote size={32} className="text-[#FFB800] mx-auto mb-3 opacity-60" />
                      <p className="text-lg sm:text-xl font-bold text-white leading-relaxed italic mb-4">
                        "{dynamicNewsItem.rayuTakeaway || dynamicNewsItem.summary}"
                      </p>
                      <span className="text-xs font-mono text-neutral-400 uppercase tracking-widest">— RAYU (@THISISRAYU)</span>
                    </div>
                    <div className="relative z-10 pt-3 border-t border-white/10 flex items-center justify-between text-[10px] font-mono text-neutral-500">
                      <span>UNFILTERED PERSPECTIVE</span>
                      <span className="text-[#FFB800]">RAYU-360.VERCEL.APP</span>
                    </div>
                  </>
                )}
              </div>
            </div>

            {/* Right Formatted Instagram Caption Preview */}
            <div className="lg:col-span-6">
              <span className="text-xs font-mono font-bold text-neutral-400 uppercase block mb-3">
                📝 GENERATED INSTAGRAM CAPTION FOR TEMPLATE
              </span>

              <div className="bg-[#050505] border border-white/15 p-5 rounded-sm font-mono text-xs text-neutral-300 leading-relaxed max-h-[420px] overflow-y-auto whitespace-pre-wrap select-all">
                {instagramCaption}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
